# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTeamsAll',
            fields=[
                ('cta_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=30)),
                ('modified_at', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=30)),
                ('cta_code', models.CharField(max_length=30)),
                ('cta_name', models.CharField(max_length=128)),
                ('pca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portals.PortalClientsAll')),
            ],
            options={
                'db_table': 'client_teams_all',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClientUsersAll',
            fields=[
                ('cua_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=30)),
                ('modified_at', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=30)),
                ('cua_username', models.CharField(max_length=30)),
                ('cua_email', models.CharField(max_length=128)),
                ('cua_fname', models.CharField(max_length=45)),
                ('cua_lname', models.CharField(max_length=45)),
                ('cua_mname', models.CharField(blank=True, max_length=45, null=True)),
                ('pca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portals.PortalClientsAll')),
            ],
            options={
                'db_table': 'client_users_all',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeamUsersAll',
            fields=[
                ('tua_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=30)),
                ('modified_at', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=30)),
                ('tua_active', models.BooleanField()),
                ('tua_role', models.CharField(max_length=45)),
                ('cta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.ClientTeamsAll')),
                ('cua', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.ClientUsersAll')),
            ],
            options={
                'db_table': 'team_users_all',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='clientteamsall',
            name='team_users',
            field=models.ManyToManyField(through='clients.TeamUsersAll', to='clients.ClientUsersAll'),
        ),
        migrations.AlterUniqueTogether(
            name='teamusersall',
            unique_together=set([('cta', 'cua')]),
        ),
        migrations.AlterUniqueTogether(
            name='clientusersall',
            unique_together=set([('pca', 'cua_email')]),
        ),
        migrations.AlterUniqueTogether(
            name='clientteamsall',
            unique_together=set([('pca', 'cta_code')]),
        ),
    ]
