# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalClientsAll',
            fields=[
                ('pca_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=30)),
                ('modified_at', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=30)),
                ('pca_code', models.CharField(max_length=30)),
                ('pca_name', models.CharField(max_length=128)),
            ],
            options={
                'managed': True,
                'db_table': 'portal_clients_all',
            },
        ),
        migrations.CreateModel(
            name='PortalsAll',
            fields=[
                ('pa_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=30)),
                ('modified_at', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=30)),
                ('pa_code', models.CharField(max_length=30, unique=True)),
                ('pa_name', models.CharField(max_length=128)),
                ('pa_desc', models.CharField(max_length=512)),
            ],
            options={
                'managed': True,
                'db_table': 'portals_all',
            },
        ),
        migrations.AddField(
            model_name='portalclientsall',
            name='pa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portals.PortalsAll'),
        ),
        migrations.AlterUniqueTogether(
            name='portalclientsall',
            unique_together=set([('pca_code', 'pa')]),
        ),
    ]
