# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalsall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='portalsall',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='portalsall',
            name='pa_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
