# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorklogActionsAll',
            fields=[
                ('waa_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=30)),
                ('modified_at', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=30)),
                ('waa_type', models.SmallIntegerField()),
                ('waa_value', models.TextField()),
                ('pwa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.ProjectWorklogsAll')),
            ],
            options={
                'managed': True,
                'db_table': 'worklog_actions_all',
            },
        ),
        migrations.CreateModel(
            name='WorklogFilesAll',
            fields=[
                ('wfa_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=30)),
                ('modified_at', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=30)),
                ('wfa_name', models.CharField(max_length=128, unique=True)),
                ('wfa_mime_type', models.CharField(max_length=128)),
                ('wfa_content_type', models.CharField(max_length=128)),
                ('wfa_doc_size', models.FloatField()),
                ('wfa_public', models.BooleanField()),
                ('pwa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.ProjectWorklogsAll')),
            ],
            options={
                'managed': True,
                'db_table': 'worklog_files_all',
            },
        ),
        migrations.CreateModel(
            name='WorklogHoursAll',
            fields=[
                ('wha_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=30)),
                ('modified_at', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=30)),
                ('wha_hours', models.DecimalField(decimal_places=2, max_digits=17)),
                ('wha_rate', models.DecimalField(decimal_places=2, max_digits=17)),
                ('wha_summary', models.CharField(max_length=128)),
                ('wha_inv_date', models.DateTimeField(blank=True, null=True)),
                ('wha_inv_number', models.CharField(blank=True, max_length=30, null=True)),
                ('pwa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.ProjectWorklogsAll')),
            ],
            options={
                'managed': True,
                'db_table': 'worklog_hours_all',
            },
        ),
    ]
